export class Instruments{
 constructor(engine,els){this.engine=engine;this.els=els;this.meter=[null,null];this.scope=[];this.logic=[];this.samples=220;this.scopeData=[];this.logicData=[]}
 setMeterProbe(ref){if(!this.meter[0]||this.meter[1])this.meter=[ref,null];else this.meter[1]=ref;this.renderLabels()}
 addScope(ref){if(this.scope.some(x=>x.partId===ref.partId&&x.terminal===ref.terminal))return;if(this.scope.length>=4)this.scope.shift();this.scope.push(ref);this.scopeData=this.scope.map(()=>[]);this.renderLabels()}
 addLogic(ref){if(this.logic.some(x=>x.partId===ref.partId&&x.terminal===ref.terminal))return;if(this.logic.length>=6)this.logic.shift();this.logic.push(ref);this.logicData=this.logic.map(()=>[]);this.renderLabels()}
 clearScope(){this.scope=[];this.scopeData=[];this.renderLabels()}clearLogic(){this.logic=[];this.logicData=[];this.renderLabels()}
 refName(r){return r?`${r.partId}:${r.terminal}`:"—"}
 renderLabels(){this.els.meterProbeLabel.innerHTML=`A: ${this.refName(this.meter[0])} &nbsp; B: ${this.refName(this.meter[1])}`;this.els.scopeLabel.textContent=this.scope.length?this.scope.map(this.refName).join(" • "):"No channels";this.els.logicLabel.textContent=this.logic.length?this.logic.map(this.refName).join(" • "):"No channels"}
 tick(){const a=this.engine.getRefVoltage(this.meter[0]),b=this.engine.getRefVoltage(this.meter[1]);this.els.meterDisplay.textContent=`${(a-b).toFixed(3)} V`;this.scope.forEach((r,i)=>{(this.scopeData[i]??=[]).push(this.engine.getRefVoltage(r));if(this.scopeData[i].length>this.samples)this.scopeData[i].shift()});this.logic.forEach((r,i)=>{(this.logicData[i]??=[]).push(this.engine.getRefVoltage(r)>2.5?1:0);if(this.logicData[i].length>this.samples)this.logicData[i].shift()});this.drawScope();this.drawLogic()}
 drawScope(){const c=this.els.scopeCanvas,x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle="#182232";x.lineWidth=1;for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,h*i/5);x.lineTo(w,h*i/5);x.stroke()}const colors=["#78a0ff","#50e3a4","#ffca6a","#ff7182"];this.scopeData.forEach((arr,ch)=>{x.strokeStyle=colors[ch];x.lineWidth=2;x.beginPath();arr.forEach((v,i)=>{const px=i/(this.samples-1)*w,py=h-Math.max(-1,Math.min(6,v+1))/7*h;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()})}
 drawLogic(){const c=this.els.logicCanvas,x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);const colors=["#78a0ff","#50e3a4","#ffca6a","#ff7182","#c895ff","#7ce7ff"];this.logicData.forEach((arr,ch)=>{const row=h/(Math.max(1,this.logicData.length)),base=(ch+.78)*row,amp=row*.45;x.strokeStyle=colors[ch];x.lineWidth=2;x.beginPath();arr.forEach((v,i)=>{const px=i/(this.samples-1)*w,py=base-v*amp;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()})}
}
