import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {TransformControls} from "three/addons/controls/TransformControls.js";
import {createPart} from "./parts.js";

export class Scene3D{
 constructor(container,callbacks={}){
  this.container=container;this.callbacks=callbacks;this.parts=new Map();this.wires=[];this.selected=null;this.selectedWire=null;this.mode="select";this.pendingTerminal=null;this.snapEnabled=true;this.wireColor=0xef5350;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x080a0e);this.scene.fog=new THREE.Fog(0x080a0e,18,55);
  this.camera=new THREE.PerspectiveCamera(48,1,.05,120);this.camera.position.set(7,7,9);
  this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(this.renderer.domElement);
  this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.enableDamping=true;this.orbit.dampingFactor=.08;this.orbit.target.set(0,0,0);
  this.transform=new TransformControls(this.camera,this.renderer.domElement);this.transform.setMode("translate");this.transform.setSpace("world");this.transform.showY=false;this.scene.add(this.transform.getHelper());
  this.transform.addEventListener("dragging-changed",e=>{this.orbit.enabled=!e.value;if(!e.value&&this.selected){if(this.snapEnabled)this.snapPart(this.selected);this.updateWires();this.callbacks.onTransformEnd?.(this.selected);this.callbacks.onChanged?.("transform")}});this.transform.addEventListener("objectChange",()=>this.updateWires());
  this.scene.add(new THREE.HemisphereLight(0xcad8ff,0x101017,1.5));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(6,10,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-12;key.shadow.camera.right=12;key.shadow.camera.top=12;key.shadow.camera.bottom=-12;this.scene.add(key);const rim=new THREE.DirectionalLight(0x6d8cff,.65);rim.position.set(-8,5,-7);this.scene.add(rim);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({color:0x0c0f14,roughness:.95,metalness:.03}));ground.rotation.x=-Math.PI/2;ground.position.y=-.13;ground.receiveShadow=true;ground.userData.kind="ground";this.scene.add(ground);const grid=new THREE.GridHelper(60,120,0x263040,0x151b24);grid.position.y=-.125;this.scene.add(grid);
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.renderer.domElement.addEventListener("pointerdown",e=>this.onPointerDown(e));window.addEventListener("resize",()=>this.resize());this.resize();this.clock=new THREE.Clock();this.animate();
 }
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 resetView(){this.camera.position.set(7,7,9);this.orbit.target.set(0,0,0);this.orbit.update()}
 setMode(mode){this.mode=mode;this.pendingTerminal=null;this.transform.detach();this.highlightTerminals(mode!=="select");this.callbacks.onMode?.(mode)}
 setWireColor(hex){this.wireColor=typeof hex==="string"?parseInt(hex.replace("#",""),16):hex}
 highlightTerminals(on){for(const p of this.parts.values())for(const t of Object.values(p.userData.terminals)){t.material.emissive.setHex(on?0x263b68:0);t.material.emissiveIntensity=on?.7:0}}
 addPart(type,pos=new THREE.Vector3(),forcedId=null){const id=forcedId||`${type}_${crypto.randomUUID().slice(0,8)}`,g=createPart(type,id);g.position.copy(pos);g.position.y=Math.max(0,g.position.y);this.scene.add(g);this.parts.set(id,g);this.callbacks.onPartAdded?.(g);this.callbacks.onChanged?.("add");return g}
 findPartRoot(obj){let o=obj;while(o&&o!==this.scene){if(o.userData?.kind==="part")return o;o=o.parent}return null}
 select(part){this.selected=part;this.selectedWire=null;if(part&&this.mode==="select")this.transform.attach(part);else this.transform.detach();this.callbacks.onSelected?.(part,null)}
 selectWire(w){this.selected=null;this.selectedWire=w;this.transform.detach();this.callbacks.onSelected?.(null,w)}
 removeSelected(){if(this.selectedWire){this.scene.remove(this.selectedWire.mesh);this.selectedWire.mesh.geometry.dispose();this.wires=this.wires.filter(x=>x!==this.selectedWire);this.selectedWire=null;this.callbacks.onSelected?.(null,null);this.callbacks.onChanged?.("delete");return}if(!this.selected)return;const id=this.selected.userData.id;for(const w of this.wires.filter(w=>w.from.partId===id||w.to.partId===id)){this.scene.remove(w.mesh);w.mesh.geometry.dispose()}this.wires=this.wires.filter(w=>w.from.partId!==id&&w.to.partId!==id);this.scene.remove(this.selected);this.parts.delete(id);this.transform.detach();this.selected=null;this.callbacks.onSelected?.(null,null);this.callbacks.onChanged?.("delete")}
 rotateSelected(){if(!this.selected)return;this.selected.rotation.y+=Math.PI/2;if(this.snapEnabled)this.snapPart(this.selected);this.updateWires();this.callbacks.onChanged?.("rotate")}
 clear(silent=false){this.transform.detach();this.selected=null;this.selectedWire=null;for(const w of this.wires){this.scene.remove(w.mesh);w.mesh.geometry.dispose()}this.wires=[];for(const p of this.parts.values())this.scene.remove(p);this.parts.clear();this.callbacks.onSelected?.(null,null);if(!silent)this.callbacks.onChanged?.("clear")}
 pick(event){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.x=((event.clientX-r.left)/r.width)*2-1;this.pointer.y=-((event.clientY-r.top)/r.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.camera);return this.raycaster.intersectObjects([...this.parts.values(),...this.wires.map(w=>w.mesh)],true)}
 onPointerDown(e){if(e.button!==0)return;const hits=this.pick(e);if(this.mode!=="select"){const hit=hits.find(h=>h.object.userData.kind==="terminal");if(hit){this.chooseTerminal(hit.object);return}}const wh=hits.find(h=>h.object.userData.kind==="wire");if(wh){const w=this.wires.find(x=>x.mesh===wh.object);if(w){this.selectWire(w);return}}const hit=hits.find(h=>this.findPartRoot(h.object));this.select(hit?this.findPartRoot(hit.object):null)}
 chooseTerminal(t){if(this.mode==="wire"){if(!this.pendingTerminal){this.pendingTerminal=t;t.material.emissive.setHex(0xff9d2f);t.material.emissiveIntensity=1.2;this.callbacks.onToolPick?.("wire",1,t);return}if(this.pendingTerminal===t)return;this.addWire(this.pendingTerminal,t,this.wireColor);this.pendingTerminal.material.emissive.setHex(0x263b68);this.pendingTerminal.material.emissiveIntensity=.7;this.pendingTerminal=null;this.callbacks.onToolPick?.("wire",0,t);this.callbacks.onChanged?.("wire");return}this.callbacks.onToolPick?.(this.mode,0,t)}
 addWire(a,b,color=this.wireColor){const from={partId:a.userData.partId,terminal:a.userData.terminal},to={partId:b.userData.partId,terminal:b.userData.terminal};if(from.partId===to.partId&&from.terminal===to.terminal)return null;if(this.wires.some(w=>(w.from.partId===from.partId&&w.from.terminal===from.terminal&&w.to.partId===to.partId&&w.to.terminal===to.terminal)||(w.to.partId===from.partId&&w.to.terminal===from.terminal&&w.from.partId===to.partId&&w.from.terminal===to.terminal)))return null;const mesh=new THREE.Mesh(new THREE.BufferGeometry(),new THREE.MeshStandardMaterial({color,roughness:.5,metalness:.05}));mesh.castShadow=true;mesh.userData.kind="wire";this.scene.add(mesh);const w={from,to,color,mesh};this.wires.push(w);this.updateWire(w);return w}
 getTerminal(ref){return this.parts.get(ref.partId)?.userData.terminals?.[ref.terminal]||null}
 terminalRef(mesh){return{partId:mesh.userData.partId,terminal:mesh.userData.terminal}}
 updateWire(w){const a=this.getTerminal(w.from),b=this.getTerminal(w.to);if(!a||!b)return;const p1=new THREE.Vector3(),p2=new THREE.Vector3();a.getWorldPosition(p1);b.getWorldPosition(p2);const lift=Math.max(.26,Math.min(1.4,p1.distanceTo(p2)*.22));const curve=new THREE.CubicBezierCurve3(p1,p1.clone().add(new THREE.Vector3(0,lift,0)),p2.clone().add(new THREE.Vector3(0,lift,0)),p2);const geo=new THREE.TubeGeometry(curve,24,.024,7,false);w.mesh.geometry.dispose();w.mesh.geometry=geo}
 updateWires(){this.wires.forEach(w=>this.updateWire(w))}
 screenToGround(clientX,clientY){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.x=((clientX-r.left)/r.width)*2-1;this.pointer.y=-((clientY-r.top)/r.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.camera);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),p=new THREE.Vector3();this.raycaster.ray.intersectPlane(plane,p);return p}
 snapPart(part){if(part.userData.type==="breadboard")return;let best=null,bestD=.42;for(const bb of this.parts.values()){if(bb.userData.type!=="breadboard")continue;for(const t of Object.values(bb.userData.terminals)){const wp=new THREE.Vector3();t.getWorldPosition(wp);const d=Math.hypot(part.position.x-wp.x,part.position.z-wp.z);if(d<bestD){bestD=d;best=wp}}}if(best){part.position.x=best.x;part.position.z=best.z}else{part.position.x=Math.round(part.position.x/.1)*.1;part.position.z=Math.round(part.position.z/.1)*.1}}
 serialize(){return{version:2,snapEnabled:this.snapEnabled,wireColor:this.wireColor,parts:[...this.parts.values()].map(p=>({id:p.userData.id,type:p.userData.type,position:p.position.toArray(),rotation:[p.rotation.x,p.rotation.y,p.rotation.z],params:structuredClone(p.userData.params)})),wires:this.wires.map(w=>({from:w.from,to:w.to,color:w.color}))}}
 load(data){this.clear(true);this.snapEnabled=data.snapEnabled??true;this.wireColor=data.wireColor??0xef5350;for(const x of data.parts||[]){const p=this.addPart(x.type,new THREE.Vector3(...(x.position||[0,0,0])),x.id);if(x.rotation)p.rotation.set(...x.rotation);Object.assign(p.userData.params,x.params||{});this.callbacks.onPartRestored?.(p)}for(const w of data.wires||[]){const a=this.getTerminal(w.from),b=this.getTerminal(w.to);if(a&&b)this.addWire(a,b,w.color)}this.updateWires();this.callbacks.onSelected?.(null,null)}
 animate(){requestAnimationFrame(()=>this.animate());const dt=Math.min(this.clock.getDelta(),.05);this.orbit.update();this.callbacks.onFrame?.(dt);this.renderer.render(this.scene,this.camera)}
}
