import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {TransformControls} from "three/addons/controls/TransformControls.js";
import {createPart} from "./parts.js";

const PIN_COLORS={available:0x35d98a,connected:0xf3bf3f,unavailable:0xff5f6d};
const BOARD_TYPES=new Set(["arduino","nano","mega","esp32","pico"]);
const BREADBOARD_MOUNTABLE=new Set(["resistor","led","diode","capacitor","button","pot","ldr","npn","pnp","mosfet_n","timer555","buzzer"]);

export class Scene3D{
 constructor(container,callbacks={}){
  this.container=container;this.callbacks=callbacks;this.parts=new Map();this.wires=[];this.selected=null;this.selectedWire=null;this.mode="select";this.pendingTerminal=null;this.snapEnabled=true;this.viewLocked=false;this.viewPreset="3d";this.wireColor=0xef5350;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x080a0e);this.scene.fog=new THREE.Fog(0x080a0e,18,55);
  this.camera=new THREE.PerspectiveCamera(48,1,.05,120);this.camera.position.set(7,7,9);
  this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(this.renderer.domElement);
  this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.enableDamping=true;this.orbit.dampingFactor=.08;this.orbit.target.set(0,0,0);
  this.transform=new TransformControls(this.camera,this.renderer.domElement);this.transform.setMode("translate");this.transform.setSpace("world");this.transform.showY=false;this.scene.add(this.transform.getHelper());
  this.transform.addEventListener("dragging-changed",e=>{this.orbit.enabled=!e.value&&!this.viewLocked;if(e.value&&this.selected){this.dragOrigin={position:this.selected.position.clone(),rotation:this.selected.rotation.clone()};return}if(!e.value&&this.selected){if(this.snapEnabled)this.snapPart(this.selected);const collision=this.findCollision(this.selected);if(collision&&this.dragOrigin){this.selected.position.copy(this.dragOrigin.position);this.selected.rotation.copy(this.dragOrigin.rotation);this.callbacks.onPlacementRejected?.(this.selected,collision)}this.setCollisionPreview(this.selected,false);this.dragOrigin=null;this.updateWires();this.callbacks.onTransformEnd?.(this.selected);this.callbacks.onChanged?.("transform")}});this.transform.addEventListener("objectChange",()=>{this.updateWires();if(this.selected)this.setCollisionPreview(this.selected,!!this.findCollision(this.selected))});
  this.scene.add(new THREE.HemisphereLight(0xcad8ff,0x101017,1.5));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(6,10,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-12;key.shadow.camera.right=12;key.shadow.camera.top=12;key.shadow.camera.bottom=-12;this.scene.add(key);const rim=new THREE.DirectionalLight(0x6d8cff,.65);rim.position.set(-8,5,-7);this.scene.add(rim);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({color:0x0c0f14,roughness:.95,metalness:.03}));ground.rotation.x=-Math.PI/2;ground.position.y=-.13;ground.receiveShadow=true;ground.userData.kind="ground";this.scene.add(ground);const grid=new THREE.GridHelper(60,120,0x263040,0x151b24);grid.position.y=-.125;this.scene.add(grid);
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.renderer.domElement.addEventListener("pointerdown",e=>this.onPointerDown(e));window.addEventListener("resize",()=>this.resize());this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.resize();this.clock=new THREE.Clock();this.animate();
 }
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.fov=this.camera.aspect<1?Math.min(72,48/this.camera.aspect):48;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 resetView(){this.setView("3d")}
 setView(preset="3d"){this.viewPreset=preset;this.orbit.target.set(0,0,0);if(preset==="top")this.camera.position.set(0,14,.001);else this.camera.position.set(7,7,9);this.camera.up.set(0,1,0);this.camera.lookAt(this.orbit.target);this.orbit.update();this.callbacks.onViewChanged?.(preset)}
 setViewLocked(locked){this.viewLocked=!!locked;this.orbit.enabled=!this.viewLocked;this.callbacks.onViewLock?.(this.viewLocked);return this.viewLocked}
 setMode(mode){this.mode=mode;this.pendingTerminal=null;this.transform.detach();this.refreshTerminalStates();this.updatePinLabelVisibility();this.callbacks.onMode?.(mode)}
 setWireColor(hex){this.wireColor=typeof hex==="string"?parseInt(hex.replace("#",""),16):hex}
 highlightTerminals(on){this.refreshTerminalStates(on)}
 addPart(type,pos=new THREE.Vector3(),forcedId=null){const id=forcedId||`${type}_${crypto.randomUUID().slice(0,8)}`,g=createPart(type,id);g.position.copy(pos);g.position.y=Math.max(0,g.position.y);this.scene.add(g);this.parts.set(id,g);this.createPinLabels(g);if(!forcedId){const moved=this.placeWithoutOverlap(g);if(moved)this.callbacks.onPlacementAdjusted?.(g)}this.refreshTerminalStates();this.updatePinLabelVisibility();this.callbacks.onPartAdded?.(g);this.callbacks.onChanged?.("add");return g}
 findPartRoot(obj){let o=obj;while(o&&o!==this.scene){if(o.userData?.kind==="part")return o;o=o.parent}return null}
 select(part){this.selected=part;this.selectedWire=null;if(part&&this.mode==="select")this.transform.attach(part);else this.transform.detach();this.updatePinLabelVisibility();this.callbacks.onSelected?.(part,null)}
 selectWire(w){this.selected=null;this.selectedWire=w;this.transform.detach();this.updatePinLabelVisibility();this.callbacks.onSelected?.(null,w)}
 removeWire(w,silent=false){if(!w||!this.wires.includes(w))return false;this.scene.remove(w.mesh);w.mesh.geometry.dispose();this.wires=this.wires.filter(x=>x!==w);if(this.selectedWire===w)this.selectedWire=null;this.refreshTerminalStates();if(!silent)this.callbacks.onChanged?.("delete");return true}
 removeSelected(){if(this.selectedWire){this.removeWire(this.selectedWire,true);this.callbacks.onSelected?.(null,null);this.callbacks.onChanged?.("delete");return}if(!this.selected)return;const id=this.selected.userData.id;for(const w of [...this.wires].filter(w=>w.from.partId===id||w.to.partId===id))this.removeWire(w,true);this.scene.remove(this.selected);this.parts.delete(id);this.transform.detach();this.selected=null;this.refreshTerminalStates();this.updatePinLabelVisibility();this.callbacks.onSelected?.(null,null);this.callbacks.onChanged?.("delete")}
 rotateSelected(){if(!this.selected)return;const old=this.selected.rotation.y;this.selected.rotation.y+=Math.PI/2;if(this.snapEnabled)this.snapPart(this.selected);const collision=this.findCollision(this.selected);if(collision){this.selected.rotation.y=old;this.callbacks.onPlacementRejected?.(this.selected,collision)}this.updateWires();this.callbacks.onChanged?.("rotate")}
 clear(silent=false){this.transform.detach();this.selected=null;this.selectedWire=null;this.pendingTerminal=null;for(const w of this.wires){this.scene.remove(w.mesh);w.mesh.geometry.dispose()}this.wires=[];for(const p of this.parts.values())this.scene.remove(p);this.parts.clear();this.callbacks.onSelected?.(null,null);if(!silent)this.callbacks.onChanged?.("clear")}
 terminalConnections(t){return this.wires.reduce((n,w)=>n+Number(w.from.partId===t.userData.partId&&w.from.terminal===t.userData.terminal)+Number(w.to.partId===t.userData.partId&&w.to.terminal===t.userData.terminal),0)}
 terminalAvailable(t){return !!t?.userData.usable&&this.terminalConnections(t)<(t.userData.maxConnections??1)}
 terminalStatus(t){if(!t.userData.usable||t===this.pendingTerminal)return"unavailable";return this.terminalConnections(t)>0?"connected":"available"}
 makePinLabel(text){const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),ratio=Math.min(devicePixelRatio||1,2);canvas.width=256*ratio;canvas.height=80*ratio;ctx.scale(ratio,ratio);ctx.fillStyle="#07100de8";ctx.beginPath();ctx.roundRect(4,4,248,72,14);ctx.fill();ctx.strokeStyle="#ffffffbb";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#fff";ctx.font=`700 ${text.length>3?25:30}px ui-monospace, monospace`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(text,128,40);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,color:PIN_COLORS.available,transparent:true,depthTest:false,depthWrite:false}));sprite.scale.set(Math.max(.28,.12*text.length),.18,1);sprite.renderOrder=30;sprite.userData={kind:"pin-label",nonCollidable:true};return sprite}
 createPinLabels(part){part.userData.pinLabels=[];if(part.userData.type==="breadboard"){for(let r=1;r<=30;r++){const sprite=this.makePinLabel(String(r)),terminal=part.userData.terminals[`e${r}`];sprite.position.set(terminal.position.x,.205,0);sprite.scale.multiplyScalar(.58);sprite.material.color.setHex(0xaab4c7);part.add(sprite);part.userData.pinLabels.push(sprite)}return}let index=0;for(const [name,t]of Object.entries(part.userData.terminals)){const sprite=this.makePinLabel(name),outward=Math.sign(t.position.z)||1,board=BOARD_TYPES.has(part.userData.type);sprite.position.copy(t.position);sprite.position.y+=board?.15:.14;sprite.position.z+=outward*(board?(.16+(index++%2)*.14):.09);part.add(sprite);t.userData.label=sprite;part.userData.pinLabels.push(sprite)}}
 updatePinLabelVisibility(){for(const part of this.parts.values()){const always=BOARD_TYPES.has(part.userData.type),show=always||this.mode!=="select"||part===this.selected;for(const label of part.userData.pinLabels||[])label.visible=show}}
 refreshTerminalStates(forceActive=this.mode!=="select"){for(const part of this.parts.values())for(const t of Object.values(part.userData.terminals)){const status=this.terminalStatus(t),color=PIN_COLORS[status];t.userData.status=status;t.userData.label?.material.color.setHex(color);if(forceActive){t.material.color.setHex(color);t.material.emissive.setHex(color);t.material.emissiveIntensity=status==="available"?.42:.68}else{t.material.color.setHex(t.userData.baseColor??0xcfd5dd);t.material.emissive.setHex(0);t.material.emissiveIntensity=0}}}
 collisionBox(part){part.updateWorldMatrix(true,true);const result=new THREE.Box3();let found=false;part.traverse(obj=>{if(!obj.isMesh||obj.userData.kind==="terminal"||obj.userData.nonCollidable||!obj.geometry)return;obj.geometry.computeBoundingBox();if(!obj.geometry.boundingBox)return;const box=obj.geometry.boundingBox.clone().applyMatrix4(obj.matrixWorld);result.union(box);found=true});return found?result:null}
 collisionAllowed(a,b){return(a.userData.type==="breadboard"&&BREADBOARD_MOUNTABLE.has(b.userData.type))||(b.userData.type==="breadboard"&&BREADBOARD_MOUNTABLE.has(a.userData.type))}
 boxesOverlapXZ(a,b,padding=.025){return a.min.x+padding<b.max.x&&a.max.x-padding>b.min.x&&a.min.z+padding<b.max.z&&a.max.z-padding>b.min.z}
 findCollision(part){const box=this.collisionBox(part);if(!box)return null;for(const other of this.parts.values()){if(other===part||this.collisionAllowed(part,other))continue;const otherBox=this.collisionBox(other);if(otherBox&&this.boxesOverlapXZ(box,otherBox))return other}return null}
 placeWithoutOverlap(part){if(!this.findCollision(part))return false;const origin=part.position.clone();for(let radius=.25;radius<=6;radius+=.25){const steps=Math.max(8,Math.ceil(radius*12));for(let i=0;i<steps;i++){const angle=i/steps*Math.PI*2;part.position.set(origin.x+Math.cos(angle)*radius,origin.y,origin.z+Math.sin(angle)*radius);if(!this.findCollision(part))return true}}part.position.copy(origin);return false}
 setCollisionPreview(part,invalid){part.traverse(obj=>{if(!obj.isMesh||obj.userData.kind==="terminal"||!obj.material?.emissive)return;if(invalid&&obj.userData.collisionEmissive===undefined){obj.userData.collisionEmissive=obj.material.emissive.getHex();obj.userData.collisionIntensity=obj.material.emissiveIntensity;obj.material.emissive.setHex(0xff263e);obj.material.emissiveIntensity=.8}else if(!invalid&&obj.userData.collisionEmissive!==undefined){obj.material.emissive.setHex(obj.userData.collisionEmissive);obj.material.emissiveIntensity=obj.userData.collisionIntensity;delete obj.userData.collisionEmissive;delete obj.userData.collisionIntensity}})}
 pick(event){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.x=((event.clientX-r.left)/r.width)*2-1;this.pointer.y=-((event.clientY-r.top)/r.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.camera);return this.raycaster.intersectObjects([...this.parts.values(),...this.wires.map(w=>w.mesh)],true)}
 onPointerDown(e){if(e.button!==0)return;const hits=this.pick(e);if(this.mode!=="select"){const hit=hits.find(h=>h.object.userData.kind==="terminal");if(hit){this.chooseTerminal(hit.object);return}}const wh=hits.find(h=>h.object.userData.kind==="wire");if(wh){const w=this.wires.find(x=>x.mesh===wh.object);if(w){this.selectWire(w);return}}const hit=hits.find(h=>this.findPartRoot(h.object));this.select(hit?this.findPartRoot(hit.object):null)}
 chooseTerminal(t){if(!t.userData.usable){this.callbacks.onTerminalRejected?.(t,t.userData.unavailableReason||"Pin unavailable");return}if(this.mode==="wire"){if(!this.pendingTerminal){if(!this.terminalAvailable(t)){this.callbacks.onTerminalRejected?.(t,"Pin already occupied");return}this.pendingTerminal=t;this.refreshTerminalStates();this.callbacks.onToolPick?.("wire",1,t);return}if(this.pendingTerminal===t){this.callbacks.onTerminalRejected?.(t,"Choose a different pin");return}const wire=this.addWire(this.pendingTerminal,t,this.wireColor);if(!wire){this.callbacks.onTerminalRejected?.(t,this.terminalAvailable(t)?"Connection not valid":"Pin already occupied");return}this.pendingTerminal=null;this.refreshTerminalStates();this.callbacks.onToolPick?.("wire",0,t);this.callbacks.onChanged?.("wire");return}this.callbacks.onToolPick?.(this.mode,0,t)}
 addWire(a,b,color=this.wireColor){const from={partId:a.userData.partId,terminal:a.userData.terminal},to={partId:b.userData.partId,terminal:b.userData.terminal};if(!a.userData.usable||!b.userData.usable||!this.terminalAvailable(a)||!this.terminalAvailable(b))return null;if(from.partId===to.partId&&from.terminal===to.terminal)return null;if(this.wires.some(w=>(w.from.partId===from.partId&&w.from.terminal===from.terminal&&w.to.partId===to.partId&&w.to.terminal===to.terminal)||(w.to.partId===from.partId&&w.to.terminal===from.terminal&&w.from.partId===to.partId&&w.from.terminal===to.terminal)))return null;const mesh=new THREE.Mesh(new THREE.BufferGeometry(),new THREE.MeshStandardMaterial({color,roughness:.42,metalness:.08}));mesh.castShadow=true;mesh.userData.kind="wire";this.scene.add(mesh);const w={from,to,color,mesh};this.wires.push(w);this.updateWire(w);this.refreshTerminalStates();return w}
 getTerminal(ref){return this.parts.get(ref.partId)?.userData.terminals?.[ref.terminal]||null}
 terminalRef(mesh){return{partId:mesh.userData.partId,terminal:mesh.userData.terminal}}
 updateWire(w){const a=this.getTerminal(w.from),b=this.getTerminal(w.to);if(!a||!b)return;const p1=new THREE.Vector3(),p2=new THREE.Vector3();a.getWorldPosition(p1);b.getWorldPosition(p2);const lift=Math.max(.26,Math.min(1.4,p1.distanceTo(p2)*.22));const curve=new THREE.CubicBezierCurve3(p1,p1.clone().add(new THREE.Vector3(0,lift,0)),p2.clone().add(new THREE.Vector3(0,lift,0)),p2);const geo=new THREE.TubeGeometry(curve,24,.024,7,false);w.mesh.geometry.dispose();w.mesh.geometry=geo}
 updateWires(){this.wires.forEach(w=>this.updateWire(w))}
 screenToGround(clientX,clientY){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.x=((clientX-r.left)/r.width)*2-1;this.pointer.y=-((clientY-r.top)/r.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.camera);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),p=new THREE.Vector3();this.raycaster.ray.intersectPlane(plane,p);return p}
 snapPart(part){if(part.userData.type==="breadboard")return;let best=null,bestD=.42;for(const bb of this.parts.values()){if(bb.userData.type!=="breadboard")continue;for(const t of Object.values(bb.userData.terminals)){const wp=new THREE.Vector3();t.getWorldPosition(wp);const d=Math.hypot(part.position.x-wp.x,part.position.z-wp.z);if(d<bestD){bestD=d;best=wp}}}if(best){part.position.x=best.x;part.position.z=best.z}else{part.position.x=Math.round(part.position.x/.1)*.1;part.position.z=Math.round(part.position.z/.1)*.1}}
 serialize(){return{version:2,snapEnabled:this.snapEnabled,wireColor:this.wireColor,parts:[...this.parts.values()].map(p=>({id:p.userData.id,type:p.userData.type,position:p.position.toArray(),rotation:[p.rotation.x,p.rotation.y,p.rotation.z],params:structuredClone(p.userData.params)})),wires:this.wires.map(w=>({from:w.from,to:w.to,color:w.color}))}}
 load(data){this.clear(true);this.snapEnabled=data.snapEnabled??true;this.wireColor=data.wireColor??0xef5350;for(const x of data.parts||[]){const p=this.addPart(x.type,new THREE.Vector3(...(x.position||[0,0,0])),x.id);if(x.rotation)p.rotation.set(...x.rotation);Object.assign(p.userData.params,x.params||{});this.callbacks.onPartRestored?.(p)}for(const w of data.wires||[]){const a=this.getTerminal(w.from),b=this.getTerminal(w.to);if(a&&b)this.addWire(a,b,w.color)}this.updateWires();this.callbacks.onSelected?.(null,null)}
 animate(){requestAnimationFrame(()=>this.animate());const dt=Math.min(this.clock.getDelta(),.05);this.orbit.update();this.callbacks.onFrame?.(dt);this.renderer.render(this.scene,this.camera)}
}
