import * as THREE from "three";
class UF{constructor(){this.p=new Map()}add(x){if(!this.p.has(x))this.p.set(x,x)}find(x){this.add(x);const p=this.p.get(x);if(p!==x)this.p.set(x,this.find(p));return this.p.get(x)}union(a,b){a=this.find(a);b=this.find(b);if(a!==b)this.p.set(b,a)}}
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-12)continue;[M[c],M[p]]=[M[p],M[c]];const d=M[c][c];for(let k=c;k<=n;k++)M[c][k]/=d;for(let r=0;r<n;r++){if(r===c)continue;const f=M[r][c];if(Math.abs(f)<1e-18)continue;for(let k=c;k<=n;k++)M[r][k]-=f*M[c][k]}}return M.map(r=>Number.isFinite(r[n])?r[n]:0)}
export class CircuitEngine{
 constructor(scene,log=()=>{}){this.scene=scene;this.log=log;this.pinOutputs=new Map();this.nodeVoltages=new Map();this.time=0;this.capState=new Map();this.dynamicSources=new Map();this.lastDt=1/120;this.audioCtx=null;this.oscillators=new Map()}
 setPinOutput(id,pin,value,mode="digital"){this.pinOutputs.set(`${id}:${pin}`,{value,mode})}clearPinOutputs(){this.pinOutputs.clear()}getPinVoltage(id,pin){return this.nodeVoltages.get(`${id}:${pin}`)??0}getRefVoltage(ref){return ref?this.getPinVoltage(ref.partId,ref.terminal):0}
 setDeviceValue(id,key,value){const p=this.scene.parts.get(id);if(p){p.userData.params[key]=value}}
 build(dt){const uf=new UF(),termByKey=new Map(),intern=new Map();for(const p of this.scene.parts.values())for(const [name,t]of Object.entries(p.userData.terminals)){const k=`${p.userData.id}:${name}`;uf.add(k);termByKey.set(k,t);if(t.userData.internalNet){const g=`${p.userData.id}:${t.userData.internalNet}`;if(intern.has(g))uf.union(k,intern.get(g));else intern.set(g,k)}}for(const w of this.scene.wires)uf.union(`${w.from.partId}:${w.from.terminal}`,`${w.to.partId}:${w.to.terminal}`);const root=x=>uf.find(x),R=[],V=[],I=[],diodes=[],ground=[];const addR=(a,b,r,meta={})=>R.push({a:root(a),b:root(b),r:Math.max(Number(r)||1e12,1e-6),meta});const addV=(a,b,v,meta={})=>V.push({a:root(a),b:root(b),v:Number(v)||0,meta});const addI=(a,b,i,meta={})=>I.push({a:root(a),b:root(b),i:Number(i)||0,meta});const T=(id,n)=>`${id}:${n}`;
  for(const p of this.scene.parts.values()){const id=p.userData.id,q=p.userData.params,type=p.userData.type;
   if(type==="resistor")addR(T(id,"1"),T(id,"2"),q.resistance,{part:p});
   if(type==="ldr"){const l=Math.max(0,Math.min(1,q.light??.5)),r=(q.maxResistance||100000)*(1-l)+(q.minResistance||500)*l;addR(T(id,"1"),T(id,"2"),r,{part:p})}
   if(type==="pot"){const pos=Math.max(.001,Math.min(.999,q.position??.5)),r=q.resistance||10000;addR(T(id,"1"),T(id,"W"),r*pos,{part:p});addR(T(id,"W"),T(id,"2"),r*(1-pos),{part:p})}
   if(type==="diode")diodes.push({a:root(T(id,"1")),b:root(T(id,"2")),is:q.is||1e-12,n:q.n||1.8,part:p});
   if(type==="led")diodes.push({a:root(T(id,"A")),b:root(T(id,"K")),is:3e-15,n:2.1,part:p,led:true});
   if(type==="capacitor"){const a=root(T(id,"+")),b=root(T(id,"-")),g=(q.capacitance||1e-6)/Math.max(dt,1e-5),prev=this.capState.get(id)||0;addR(T(id,"+"),T(id,"-"),1/g,{part:p,cap:true});addI(a,b,-g*prev,{part:p,cap:true})}
   if(type==="button"){addR(T(id,"1"),T(id,"3"),.001);addR(T(id,"2"),T(id,"4"),.001);addR(T(id,"1"),T(id,"2"),q.pressed?.001:1e10,{part:p})}
   if(type==="battery"){addV(T(id,"+"),T(id,"-"),q.voltage||9,{part:p});ground.push(root(T(id,"-")))}
   if(type==="ground")ground.push(root(T(id,"GND")));
   if(type==="logic"){addV(T(id,"OUT"),T(id,"GND"),q.high?(q.voltage||5):0,{part:p});ground.push(root(T(id,"GND")))}
   if(type==="functiongen"){const f=q.frequency||1,x=2*Math.PI*f*this.time;let w=Math.sin(x);if(q.wave==="square")w=Math.sin(x)>=0?1:-1;else if(q.wave==="triangle")w=2/Math.PI*Math.asin(Math.sin(x));addV(T(id,"OUT"),T(id,"GND"),(q.offset||0)+(q.amplitude||0)*w,{part:p});ground.push(root(T(id,"GND")))}
   if(type==="analogSensor"){addV(T(id,"OUT"),T(id,"GND"),Math.max(0,Math.min(5,q.value??2.5)),{part:p});ground.push(root(T(id,"GND")))}
   if(type==="motor")addR(T(id,"+"),T(id,"-"),q.resistance||80,{part:p});
   if(type==="buzzer")addR(T(id,"+"),T(id,"-"),120,{part:p});
   if(type==="servo"){addR(T(id,"VCC"),T(id,"GND"),220,{part:p});}
   if(type==="npn"||type==="pnp"){const vb=this.getPinVoltage(id,"B"),ve=this.getPinVoltage(id,"E"),on=type==="npn"?vb-ve>.62:ve-vb>.62;addR(T(id,"C"),T(id,"E"),on?Math.max(.4,120/(q.beta||100)):1e9,{part:p});diodes.push({a:root(T(id,type==="npn"?"B":"E")),b:root(T(id,type==="npn"?"E":"B")),is:1e-12,n:1.6,part:p})}
   if(type==="mosfet_n"){const vg=this.getPinVoltage(id,"G"),vs=this.getPinVoltage(id,"S");addR(T(id,"D"),T(id,"S"),vg-vs>(q.threshold||2.5)?(q.onResistance||1):1e9,{part:p})}
   if(type==="timer555"){const gnd=this.getPinVoltage(id,"1"),tr=this.getPinVoltage(id,"2")-gnd,th=this.getPinVoltage(id,"6")-gnd,reset=this.getPinVoltage(id,"4")-gnd,vcc=Math.max(.1,this.getPinVoltage(id,"8")-gnd);if(reset<.7)p.userData.state.out=false;else if(tr<vcc/3)p.userData.state.out=true;else if(th>2*vcc/3)p.userData.state.out=false;addV(T(id,"3"),T(id,"1"),p.userData.state.out?vcc:0,{part:p});addR(T(id,"7"),T(id,"1"),p.userData.state.out?1e9:20,{part:p})}
   if(["arduino","nano","mega","esp32","pico"].includes(type)){const is33=["esp32","pico"].includes(type),power=is33?"3V3":"5V",logic=q.logicVoltage||(is33?3.3:5);addV(T(id,power),T(id,"GND"),logic,{part:p});addR(T(id,"GND"),T(id,"GND2"),.001);ground.push(root(T(id,"GND")));for(const [key,o]of this.pinOutputs)if(key.startsWith(id+":")){const pin=key.split(":")[1],v=o.mode==="pwm"?logic*o.value/255:(o.value?logic:0);if(p.userData.terminals[pin])addV(T(id,pin),T(id,"GND"),v,{part:p,pin})}}
  }
  return{uf,termByKey,root,R,V,I,diodes,ground};
 }
 step(dt=1/120){dt=Math.max(1e-5,Math.min(.05,dt));this.lastDt=dt;this.time+=dt;const N=this.build(dt),nodes=new Set();for(const e of [...N.R,...N.V,...N.I,...N.diodes]){nodes.add(e.a);nodes.add(e.b)}for(const k of N.termByKey.keys())nodes.add(N.root(k));if(!nodes.size)return;const ground=N.ground[0]||[...nodes][0],active=[...nodes].filter(n=>n!==ground),idx=new Map(active.map((n,i)=>[n,i]));let guess=new Map(active.map(n=>[n,0]));for(let iter=0;iter<7;iter++){const nv=active.length,ns=N.V.length,size=nv+ns,A=Array.from({length:size},()=>Array(size).fill(0)),b=Array(size).fill(0),ni=n=>n===ground?-1:idx.get(n);const stampG=(a,c,g)=>{a=ni(a);c=ni(c);if(a>=0)A[a][a]+=g;if(c>=0)A[c][c]+=g;if(a>=0&&c>=0){A[a][c]-=g;A[c][a]-=g}},stampI=(a,c,i)=>{a=ni(a);c=ni(c);if(a>=0)b[a]-=i;if(c>=0)b[c]+=i};for(const e of N.R)stampG(e.a,e.b,1/e.r);for(const e of N.I)stampI(e.a,e.b,e.i);for(const d of N.diodes){const va=d.a===ground?0:(guess.get(d.a)||0),vb=d.b===ground?0:(guess.get(d.b)||0),vd=Math.max(-1,Math.min(.85,va-vb)),vt=.02585*d.n,ex=Math.exp(vd/vt),cur=d.is*(ex-1),g=Math.min(50,Math.max(1e-9,d.is/ vt*ex)),ieq=cur-g*vd;stampG(d.a,d.b,g);stampI(d.a,d.b,ieq)}N.V.forEach((s,k)=>{const row=nv+k,a=ni(s.a),c=ni(s.b);if(a>=0){A[a][row]+=1;A[row][a]+=1}if(c>=0){A[c][row]-=1;A[row][c]-=1}b[row]=s.v});for(let i=0;i<nv;i++)A[i][i]+=1e-10;const x=solve(A,b);guess=new Map(active.map((n,i)=>[n,x[i]||0]));if(iter===6){this.nodeVoltages.clear();for(const key of N.termByKey.keys()){const n=N.root(key);this.nodeVoltages.set(key,n===ground?0:(guess.get(n)||0))}}}
  for(const p of this.scene.parts.values())this.updateVisual(p,dt);for(const p of this.scene.parts.values())if(p.userData.type==="capacitor")this.capState.set(p.userData.id,this.getPinVoltage(p.userData.id,"+")-this.getPinVoltage(p.userData.id,"-"));
 }
 updateVisual(p,dt){const id=p.userData.id,t=p.userData.type;if(t==="led"){const v=this.getPinVoltage(id,"A")-this.getPinVoltage(id,"K"),on=Math.max(0,Math.min(1,(v-(p.userData.params.forwardVoltage||1.9))/1.2)),bulb=p.userData.visual.bulb;if(bulb){const c=new THREE.Color(p.userData.params.color||"#ff384f");bulb.material.color.copy(c).multiplyScalar(.3+.7*on);bulb.material.emissive.copy(c);bulb.material.emissiveIntensity=on*4}}
  if(["arduino","nano","mega","esp32","pico"].includes(t)){const o=this.pinOutputs.get(`${id}:D13`),on=o?(o.mode==="pwm"?o.value/255:(o.value?1:0)):0,led=p.userData.visual.onboardLed;if(led){led.material.emissive.setHex(0xffbd3f);led.material.emissiveIntensity=on*3;led.material.color.setHex(on?0xe6ad32:0x463c16)}}
  if(t==="motor"&&p.userData.visual.shaft){const v=Math.abs(this.getPinVoltage(id,"+")-this.getPinVoltage(id,"-"));p.userData.visual.shaft.rotation.y+=Math.min(35,v*3)*dt}
  if(t==="servo"&&p.userData.visual.horn){const v=this.getPinVoltage(id,"SIG");const a=p.userData.params.angle??Math.max(0,Math.min(180,v/5*180));p.userData.visual.horn.rotation.y=(a-90)*Math.PI/180}
  if(t==="neopixel"){(p.userData.params.pixels||[]).forEach((c,i)=>{const px=p.userData.visual.pixels?.[i];if(px){const col=new THREE.Color(c);px.material.color.copy(col).multiplyScalar(.35);px.material.emissive.copy(col);px.material.emissiveIntensity=2}})}
  if(t==="buzzer")this.updateBuzzer(p)
 }
 updateBuzzer(p){const v=Math.abs(this.getPinVoltage(p.userData.id,"+")-this.getPinVoltage(p.userData.id,"-")),should=v>.7&&p.userData.params.enabled;if(!should){const o=this.oscillators.get(p.userData.id);if(o){try{o.gain.gain.setTargetAtTime(0,o.ctx.currentTime,.02);setTimeout(()=>{try{o.osc.stop()}catch{}},80)}catch{};this.oscillators.delete(p.userData.id)}return}if(!globalThis.AudioContext&&!globalThis.webkitAudioContext)return;if(!this.audioCtx){const C=globalThis.AudioContext||globalThis.webkitAudioContext;this.audioCtx=new C()}if(this.audioCtx.state==="suspended")this.audioCtx.resume().catch(()=>{});let o=this.oscillators.get(p.userData.id);if(!o){const osc=this.audioCtx.createOscillator(),gain=this.audioCtx.createGain();gain.gain.value=.025;osc.connect(gain).connect(this.audioCtx.destination);osc.start();o={osc,gain,ctx:this.audioCtx};this.oscillators.set(p.userData.id,o)}o.osc.frequency.setTargetAtTime(p.userData.params.frequency||440,this.audioCtx.currentTime,.02)}
 generateSpiceNetlist(){const N=this.build(1e-3),nodeNames=new Map(),n=0,name=x=>{if(N.ground.includes(x))return"0";if(!nodeNames.has(x))nodeNames.set(x,String(++n));return nodeNames.get(x)};const out=["OpenCircuit 3D autogenerated netlist"];let ri=0,vi=0,ci=0,di=0;for(const e of N.R)out.push(`R${++ri} ${name(e.a)} ${name(e.b)} ${e.r}`);for(const e of N.V)out.push(`V${++vi} ${name(e.a)} ${name(e.b)} DC ${e.v}`);for(const p of this.scene.parts.values())if(p.userData.type==="capacitor"){const a=N.root(`${p.userData.id}:+`),b=N.root(`${p.userData.id}:-`);out.push(`C${++ci} ${name(a)} ${name(b)} ${p.userData.params.capacitance||1e-6}`)}for(const d of N.diodes){out.push(`D${++di} ${name(d.a)} ${name(d.b)} DMOD`)}if(di)out.push(".model DMOD D(Is=1e-12 N=1.8)");out.push(".op",".end");return out.join("\n")}
}
